package Lab1;

/**
 * Class used to test first Lab list.
 */
public class Lab1Main {
    /**
     * If you want to test first Lab list, just run this method. I predicted a bit of the cases.
     *
     * @param args You don't need this argument.
     */
    public static void main(String[] args) {
        try {
            testLCG();
            testGLIBC();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    static void testLCG() throws Exception {
        LCG generator = new LCG(1, 2, 10, 1);

        System.out.println("\nGenerate two strings using LCB:");
        String s1 = generator.generateString(10);
        System.out.println(s1);
        System.out.println(generator.generateString(15) + "\n\n");

        String s2 = "1_2_3_4_5_1_2_3_4_5_1_2_3_4_5";
        System.out.println(printDistinguisher(s2, "LCB", (LCG.isLCB(s2, SolutionClass.Cycle))));

        String s3 = "1_2_4_8_16_32_0_0_0_0";
        System.out.println(printDistinguisher(s3, "LCB", (LCG.isLCB(s3, SolutionClass.Cycle))));

        String s4 = "0_0_0_4_3_9_1_17_4";
        System.out.println(printDistinguisher(s4, "LCB", (LCG.isLCB(s4, SolutionClass.Cycle))));
    }

    static void testGLIBC() throws Exception {

        GLIBC generator = new GLIBC(2000, 99900);
        String s4 = generator.generateString();
        System.out.println(printDistinguisher(s4, "GLIBC", (GLIBC.isGLIBC(s4))));
        System.out.println(printDistinguisher("1_2_3_4_5_1_2_3_4_5_1_2_3_4_5", "GLIBC", (GLIBC.isGLIBC(s4))));
        System.out.println(printDistinguisher("1_2_4_8_16_32_0_0_0_0", "GLIBC", (GLIBC.isGLIBC(s4))));
    }

    static String printDistinguisher(String str, String gen, boolean was) {
        String affirmative = "was";
        if (!was)
            affirmative = "was not";
        return ("String: \n'" + str + "'\n" + affirmative + " generated by " + gen + ".\n\n");
    }
}