package Lab1;

/**
 * Class used to test first Lab list.
 */
public class Lab1Main {
    /**
     * If you want to test first Lab list, just run this method. I predicted a bit of the cases.
     *
     * @param args You don't need this argument.
     */
    public static void main(String[] args) {
        try {
            testLCG();
            testGLIBC();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    static void testLCG() throws Exception {
        LCG generator = new LCG(1, 2, 10, 1);

        System.out.println("\nGenerate two strings using LCB:");
        String s1 = generator.generateString(10);
        System.out.println(s1);
        System.out.println(generator.generateString(15) + "\n\n");

        String s2 = "1_2_3_4_5_1_2_3_4_5_1_2_3_4_5";
        if (LCG.isLCB(s2, SolutionClass.Cycle))
            System.out.println(printDistinguisher(s2, "LCB"));

        String s3 = "1_2_4_8_16_32_0_0_0_0";
        if (LCG.isLCB(s3, SolutionClass.Cycle))
            System.out.println(printDistinguisher(s3, "LCB"));

    }

    static void testGLIBC() {

        GLIBC generator2 = new GLIBC();
        String s4 = generator2.generateString();

        if (GLIBC.isGLIBC(s4))
            System.out.println(printDistinguisher(s4, "GLIBC"));

    }



    static String printDistinguisher(String str, String gen) {
        return ("String: \n'" + str + "'\n was generated by " + gen + ".\n\n");
    }
}