import Lab1.GLIBC;
import Lab1.LCG;
import Lab1.SolutionClass;

import java.util.Random;

/**
 * Class used to test current Lab list. Each package describes specific list and has its own Main class.
 */
public class Main {
    /**
     * If you simply want to test current Lab list, just run this method.
     * @param args You don't need this argument.
     */
    public static void main(String[] args) {
        try {
            LCG generator = new LCG(1, 2, 10, 1);

            System.out.println("\nGenerate two strings using LCB:");
            String s1 = generator.generateString(10);
            System.out.println(s1);
            System.out.println(generator.generateString(15) + "\n\n");

            String s2 = "1_2_3_4_5_1_2_3_4_5_1_2_3_4_5";
            if (LCG.isLCB(s2, SolutionClass.Cycle))
                System.out.println("String: \n'" + s2 + "'\n was generated by LCB.\n\n");

            String s3 = "1_2_4_8_16_32_0_0_0_0";
            if (LCG.isLCB(s3, SolutionClass.Cycle))
                System.out.println("String: \n'" + s3 + "'\n was generated by LCB.\n\n");

            GLIBC generator2 = new GLIBC();
            String s4 = generator2.generateString();

            if (GLIBC.isGLIBC(s4))
                System.out.println("String: \n'" + s4 + "'\n was generated by GLIBC.\n\n");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}