import Lab1.GLIBC;
import Lab1.Generator;
import Lab1.LCG;
import Lab1.SolutionClass;

import java.math.BigInteger;
import java.util.LinkedList;
import java.util.List;
import java.util.Random;

/**
 * Class used to test current Lab list. Each package describes specific list and has its own Main class.
 */
public class Main {
    /**
     * If you simply want to test current Lab list, just run this method.
     * @param args You don't need this argument.
     */
    public static void main(String[] args) {
        try {


            Generator lcg = new LCG();
            List<BigInteger> list1 = lcg.generateList(100);

            if (lcg.isGenerated(list1) )
                System.out.println("String: \n'" + list1 + "'\n was generated by LCG.\n\n");

            List<BigInteger> list2 = new LinkedList<>();
            for (int i = 0; i < 20; i++) {
                list2.add(new BigInteger("1"));
                list2.add(new BigInteger("-1"));
            }

            if (lcg.isGenerated(list2) )
                System.out.println("String: \n'" + list2 + "'\n was generated by LCG.\n\n");

            Generator generator2 = new GLIBC();
            List<BigInteger> s4 = generator2.generateList(100);

            if (generator2.isGenerated(s4))
                System.out.println("String: \n'" + s4 + "'\n was generated by GLIBC.\n\n");

        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}